# Generated by Django 4.2.4 on 2023-08-08 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0002_inventory_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='data',
        ),
    ]
