# Generated by Django 4.2.4 on 2023-08-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0004_inventory_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
